apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-dev
  name: nginx-dev
  namespace: rahul
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dev
  type: NodePort
